env:
  commonjs: true
  es6: true
  node: true
  mocha: true
root: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules: {
  no-param-reassign: 0,
  no-underscore-dangle: 0,
  func-names: 0,
}